# Nixpacks configuration for Backend
# https://nixpacks.com/docs/configuration/file

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT"
